#!/usr/bin/perl

my $chap = 0;
my $par = 1;

foreach my $line (<>) {
    if ($line =~ s/\[(\d+)\].*/<div id="$chap:\1" class="anchor"><\/div>/) {
        print $line;
    }

    if ($line =~ /\[\$(.*?)\]/) {
        $chap = $1;
    }

    if ($line =~ s/\[\$(.*?)\].*/<div id="\1" class="anchor"><\/div>/g) {
        print $line;
    }

    if ($line =~ /^$/) {
        $par = 1;
    } else {
        $par = 0;
    }
}
