#!/usr/bin/perl

my $chap = 0;
my $par = 1;

print "<div id=\"contents\">\n";
print "<div id=\"default-contents\" class=\"default contents\"></div><div style=\"display: none;\"><div>\n";

foreach my $line (<>) {
    if ($par && $line =~ /^(\[\d+\])「/) {
        print "<p class=\"noindent\">\n";
        print "<span>\n";
        $line =~ s/\[(\d+)\]/<\/span><span id="$chap:\1-anchor" class="sect"><sup><a href="#$chap:\1">\1<\/a><\/sup>&nbsp;/;
    } elsif ($par && $line =~ /^(\[\d+\])/) {
        print "<p class=\"noindent\">\n";
        print "<span>\n";
        $line =~ s/\[(\d+)\]/<\/span><span class="indent"><\/span><span id="$chap:\1-anchor" class="sect"><sup><a href="#$chap:\1">\1<\/a><\/sup>/;
    } elsif ($par) {
        print "<p class=\"indent\">\n";
    }
    $line =~ s/\[(\d+)\]/<\/span><span id="$chap:\1-anchor" class="sect"><sup><a href="#$chap:\1">\1<\/a><\/sup>&nbsp;/g;
    $line =~ s/\[\*\]/<div class="space"><\/div>\n<span>\n/g;
    $line =~ s/\[\+\]/<div class="space"><\/div>\n<span>\n/g;

    if ($line =~ /\[\$((\d|\.)*?)(:(.*?))?\]/) {
        $chap = $1;
        print "</p></div></div><div id=\"$chap-contents\" class=\"contents\">";
        print "<div class=\"markdown-body\">";
    }

    $line =~ s/\[\$((?:\d|\.)*?):(.*?)\]/<h2 id="\1">\2<\/h2>\n<span>\n/g;
    $line =~ s/\[\$((\d|\.)*?)\]/<h2 id="\1">第\1章<\/h2>\n<span>\n/g;

    $line =~ s/(……)/<span class="cdots">\1<\/span>/g;
    $line =~ s/(――)/<span class="dashes">\1<\/span>/g;

    $line =~ s/！？(?!」)/！？<span class="indent"><\/span>/g;
    $line =~ s/！(?!？|」)/！<span class="indent"><\/span>/g;
    $line =~ s/？(?!」)/？<span class="indent"><\/span>/g;

    if ($line =~ /^$/) {
        print "</span>\n";
        print "</p>\n";
        $par = 1;
    } else {
        $par = 0;
    }

    print $line;
}

print "</div></div></div>\n";
