#!/bin/sh

printf "<!DOCTYPE html>\n"
printf "\n"
printf "<meta charset=\"utf-8\">\n"
printf "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
printf "<title>%s</title>\n" "$1"
printf "\n"

printf "<style>"
cat ./template.css
./mkstyle < "$2"
printf "</style>"

printf "<div id=\"container\">\n"

./mkanchors < "$2"

printf "  <div id=\"hd\"></div>\n"
printf "  <h1>%s</h1>\n" "$1"

./mkindex < "$2"
./mkcontents < "$2"

printf "</div>\n"
