#!/usr/bin/perl

my $chap = 0;
my $par = 1;

print "<div id=\"index\">\n";
print "<div id=\"default-index-group\" class=\"default level-0 index-group\">\n";
print "<div id=\"default-index\" class=\"default index\"><a href=\"#home\">HOME</a></div>\n";

foreach my $line (<>) {
    if ($line =~ s/\[(\d+)\].*/<div id="$chap:\1-index" class="index">$chap:\1<\/div>/) {
    }

    if ($line =~ /\[\$((\d|\.)*?)(:(.*?))?\]/) {
        $chap = $1;
    }

    if ($line =~ s/\[\$((\d|\.)*?)(:(.*?))?\].*/<div id="\1-index" class="index"><a href="#\1">\1<\/a><\/div>/g) {
        print $line;
    }

    if ($line =~ /^$/) {
        $par = 1;
    } else {
        $par = 0;
    }
}

print "</div>\n";
print "</div>\n";
