/* tslint:disable */
export const memory: WebAssembly.Memory;
export function __wbindgen_global_argument_ptr(): number;
export function __wbg_game_free(a: number): void;
export function __wbg_viewmap_free(a: number): void;
export function __wbg_views_free(a: number): void;
export function view_map_length(a: number): number;
export function view_map_x(a: number): number;
export function view_map_y(a: number): number;
export function view_map_z(a: number, b: number): number;
export function view_map_views(a: number, b: number): number;
export function views_length(a: number): number;
export function views_eq(a: number, b: number): number;
export function view_is_image(a: number, b: number): number;
export function view_image_name(a: number, b: number, c: number): void;
export function view_image_x(a: number, b: number, c: number): void;
export function view_image_y(a: number, b: number, c: number): void;
export function view_image_z(a: number, b: number, c: number): void;
export function new_(): number;
export function step(a: number, b: number, c: number): number;
export function view_map(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
