// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

function intro(param) {
  return Promise.resolve(/* record */[
              /* i */0,
              /* x */param[0],
              /* y */param[1],
              /* pose : Walk */0,
              /* direction : Front */3
            ]);
}

function step(inputs, teiri) {
  var xshift = Caml_array.caml_array_get(inputs, 0).x < -0.25 ? -1 : (
      Caml_array.caml_array_get(inputs, 0).x > 0.25 ? 1 : 0
    );
  var yshift = Caml_array.caml_array_get(inputs, 0).y < -0.25 ? -1 : (
      Caml_array.caml_array_get(inputs, 0).y > 0.25 ? 1 : 0
    );
  return Promise.resolve(/* record */[
              /* i */teiri[/* i */0] + 1 | 0,
              /* x */teiri[/* x */1] + xshift | 0,
              /* y */teiri[/* y */2] + yshift | 0,
              /* pose */Caml_array.caml_array_get(Caml_array.caml_array_get(inputs, 0).buttons, 4) ? /* Hijack */1 : /* Walk */0,
              /* direction */yshift < 0 ? /* Back */1 : (
                  yshift > 0 ? /* Front */3 : (
                      xshift < 0 ? /* Left */0 : (
                          xshift > 0 ? /* Right */2 : teiri[/* direction */4]
                        )
                    )
                )
            ]);
}

function x(teiri) {
  var match = teiri[/* pose */3];
  if (match) {
    return teiri[/* x */1] - 8 | 0;
  } else {
    return teiri[/* x */1];
  }
}

function y(teiri) {
  var match = teiri[/* pose */3];
  if (match) {
    return teiri[/* y */2] - 8 | 0;
  } else {
    return teiri[/* y */2];
  }
}

function string_of_direction(param) {
  switch (param) {
    case 0 : 
        return "left";
    case 1 : 
        return "back";
    case 2 : 
        return "right";
    case 3 : 
        return "front";
    
  }
}

function views(teiri) {
  return Promise.resolve(/* array */[/* `Image */[
                -795439301,
                /* tuple */[
                  x(teiri),
                  y(teiri),
                  "pixelart/teiri/" + ((
                      teiri[/* pose */3] ? "hijack" : "walk"
                    ) + ("/" + (string_of_direction(teiri[/* direction */4]) + ("/" + (String((teiri[/* i */0] / 8 | 0) % 4) + ".png")))))
                ]
              ]]);
}

var Teiri = /* module */[
  /* intro */intro,
  /* step */step,
  /* views */views
];

function intro$1(param) {
  return intro(param[0]).then((function (teiri) {
                return Promise.resolve(/* Teiri */[teiri]);
              }));
}

function step$1(inputs, param) {
  return step(inputs, param[0]).then((function (teiri) {
                return Promise.resolve(/* Teiri */[teiri]);
              }));
}

function views$1(param) {
  return views(param[0]);
}

var $$Object = /* module */[
  /* intro */intro$1,
  /* step */step$1,
  /* views */views$1
];

function intro$2(param) {
  return Promise.all($$Array.map(intro$1, param[/* params */0])).then((function (objects) {
                return Promise.resolve(/* record */[/* objects */objects]);
              }));
}

function step$2(inputs, map) {
  return Promise.all($$Array.map((function (obj) {
                      return step$1(inputs, obj);
                    }), map[/* objects */0])).then((function (objects) {
                return Promise.resolve(/* record */[/* objects */objects]);
              }));
}

function views$2(map) {
  return Promise.all($$Array.map((function (obj) {
                      return views(obj[0]);
                    }), map[/* objects */0])).then((function (views) {
                return Promise.resolve($$Array.concat($$Array.to_list(views)));
              }));
}

var test = /* record */[/* params : array */[/* TeiriParam */[/* tuple */[
        32,
        32
      ]]]];

var $$Map = /* module */[
  /* intro */intro$2,
  /* step */step$2,
  /* views */views$2,
  /* test */test
];

function intro$3(param) {
  return intro$2(test);
}

var width = 320;

var height = 240;

var assets = /* array */[
  /* tuple */[
    "pixelart/teiri/walk.png",
    /* array */[
      /* tuple */[
        "pixelart/teiri/walk/left/0.png",
        /* tuple */[
          0,
          0,
          16,
          16
        ]
      ],
      /* tuple */[
        "pixelart/teiri/walk/left/1.png",
        /* tuple */[
          16,
          0,
          16,
          16
        ]
      ],
      /* tuple */[
        "pixelart/teiri/walk/left/2.png",
        /* tuple */[
          32,
          0,
          16,
          16
        ]
      ],
      /* tuple */[
        "pixelart/teiri/walk/left/3.png",
        /* tuple */[
          48,
          0,
          16,
          16
        ]
      ],
      /* tuple */[
        "pixelart/teiri/walk/back/0.png",
        /* tuple */[
          0,
          16,
          16,
          16
        ]
      ],
      /* tuple */[
        "pixelart/teiri/walk/back/1.png",
        /* tuple */[
          16,
          16,
          16,
          16
        ]
      ],
      /* tuple */[
        "pixelart/teiri/walk/back/2.png",
        /* tuple */[
          32,
          16,
          16,
          16
        ]
      ],
      /* tuple */[
        "pixelart/teiri/walk/back/3.png",
        /* tuple */[
          48,
          16,
          16,
          16
        ]
      ],
      /* tuple */[
        "pixelart/teiri/walk/right/0.png",
        /* tuple */[
          0,
          32,
          16,
          16
        ]
      ],
      /* tuple */[
        "pixelart/teiri/walk/right/1.png",
        /* tuple */[
          16,
          32,
          16,
          16
        ]
      ],
      /* tuple */[
        "pixelart/teiri/walk/right/2.png",
        /* tuple */[
          32,
          32,
          16,
          16
        ]
      ],
      /* tuple */[
        "pixelart/teiri/walk/right/3.png",
        /* tuple */[
          48,
          32,
          16,
          16
        ]
      ],
      /* tuple */[
        "pixelart/teiri/walk/front/0.png",
        /* tuple */[
          0,
          48,
          16,
          16
        ]
      ],
      /* tuple */[
        "pixelart/teiri/walk/front/1.png",
        /* tuple */[
          16,
          48,
          16,
          16
        ]
      ],
      /* tuple */[
        "pixelart/teiri/walk/front/2.png",
        /* tuple */[
          32,
          48,
          16,
          16
        ]
      ],
      /* tuple */[
        "pixelart/teiri/walk/front/3.png",
        /* tuple */[
          48,
          48,
          16,
          16
        ]
      ]
    ]
  ],
  /* tuple */[
    "pixelart/teiri/hijack.png",
    /* array */[
      /* tuple */[
        "pixelart/teiri/hijack/left/0.png",
        /* tuple */[
          0,
          0,
          32,
          32
        ]
      ],
      /* tuple */[
        "pixelart/teiri/hijack/left/1.png",
        /* tuple */[
          32,
          0,
          32,
          32
        ]
      ],
      /* tuple */[
        "pixelart/teiri/hijack/left/2.png",
        /* tuple */[
          64,
          0,
          32,
          32
        ]
      ],
      /* tuple */[
        "pixelart/teiri/hijack/left/3.png",
        /* tuple */[
          96,
          0,
          32,
          32
        ]
      ],
      /* tuple */[
        "pixelart/teiri/hijack/back/0.png",
        /* tuple */[
          0,
          32,
          32,
          32
        ]
      ],
      /* tuple */[
        "pixelart/teiri/hijack/back/1.png",
        /* tuple */[
          32,
          32,
          32,
          32
        ]
      ],
      /* tuple */[
        "pixelart/teiri/hijack/back/2.png",
        /* tuple */[
          64,
          32,
          32,
          32
        ]
      ],
      /* tuple */[
        "pixelart/teiri/hijack/back/3.png",
        /* tuple */[
          96,
          32,
          32,
          32
        ]
      ],
      /* tuple */[
        "pixelart/teiri/hijack/right/0.png",
        /* tuple */[
          0,
          64,
          32,
          32
        ]
      ],
      /* tuple */[
        "pixelart/teiri/hijack/right/1.png",
        /* tuple */[
          32,
          64,
          32,
          32
        ]
      ],
      /* tuple */[
        "pixelart/teiri/hijack/right/2.png",
        /* tuple */[
          64,
          64,
          32,
          32
        ]
      ],
      /* tuple */[
        "pixelart/teiri/hijack/right/3.png",
        /* tuple */[
          96,
          64,
          32,
          32
        ]
      ],
      /* tuple */[
        "pixelart/teiri/hijack/front/0.png",
        /* tuple */[
          0,
          96,
          32,
          32
        ]
      ],
      /* tuple */[
        "pixelart/teiri/hijack/front/1.png",
        /* tuple */[
          32,
          96,
          32,
          32
        ]
      ],
      /* tuple */[
        "pixelart/teiri/hijack/front/2.png",
        /* tuple */[
          64,
          96,
          32,
          32
        ]
      ],
      /* tuple */[
        "pixelart/teiri/hijack/front/3.png",
        /* tuple */[
          96,
          96,
          32,
          32
        ]
      ]
    ]
  ]
];

var scale = 2;

exports.Teiri = Teiri;
exports.$$Object = $$Object;
exports.$$Map = $$Map;
exports.intro = intro$3;
exports.step = step$2;
exports.views = views$2;
exports.scale = scale;
exports.width = width;
exports.height = height;
exports.assets = assets;
/* No side effect */
