use super::*;

pub fn new() -> Hijack {
  Hijack {
    objects: vec![
      (
        brownfox::Control::Immovable(brownfox::Immovable::new()),
        object::Object::Maptip(object::maptip::new(
          0,
          0,
          0,
          16,
          16,
          vec![
            brownfox::Rectangle::new(0, 0, 20, 15),
          ],
          "pixelart/maptip/ground/center.png".to_string(),
          "pixelart/maptip/ground/left.png".to_string(),
          "pixelart/maptip/ground/top.png".to_string(),
          "pixelart/maptip/ground/right.png".to_string(),
          "pixelart/maptip/ground/bottom.png".to_string(),
          "pixelart/maptip/ground/top-left.png".to_string(),
          "pixelart/maptip/ground/top-right.png".to_string(),
          "pixelart/maptip/ground/bottom-left.png".to_string(),
          "pixelart/maptip/ground/bottom-right.png".to_string(),
          "pixelart/maptip/ground/top-left_inv.png".to_string(),
          "pixelart/maptip/ground/top-right_inv.png".to_string(),
          "pixelart/maptip/ground/bottom-left_inv.png".to_string(),
          "pixelart/maptip/ground/bottom-right_inv.png".to_string(),
        )),
      ),
      (
        brownfox::Control::Immovable(brownfox::Immovable::new()),
        object::Object::Maptip(object::maptip::new(
          0,
          0,
          0,
          16,
          16,
          vec![
            brownfox::Rectangle::new(0, 7, 20, 4),
            brownfox::Rectangle::new(8, 0, 4, 10),
          ],
          "pixelart/maptip/asphalt/center.png".to_string(),
          "pixelart/maptip/asphalt/left.png".to_string(),
          "pixelart/maptip/asphalt/top.png".to_string(),
          "pixelart/maptip/asphalt/right.png".to_string(),
          "pixelart/maptip/asphalt/bottom.png".to_string(),
          "pixelart/maptip/asphalt/top-left.png".to_string(),
          "pixelart/maptip/asphalt/top-right.png".to_string(),
          "pixelart/maptip/asphalt/bottom-left.png".to_string(),
          "pixelart/maptip/asphalt/bottom-right.png".to_string(),
          "pixelart/maptip/asphalt/top-left_inv.png".to_string(),
          "pixelart/maptip/asphalt/top-right_inv.png".to_string(),
          "pixelart/maptip/asphalt/bottom-left_inv.png".to_string(),
          "pixelart/maptip/asphalt/bottom-right_inv.png".to_string(),
        )),
      ),
      (
        brownfox::Control::Immovable(brownfox::Immovable::new()),
        object::Object::Maptip(object::maptip::new(
          0,
          0,
          0,
          16,
          16,
          vec![
            brownfox::Rectangle::new(2, -8, 5, 5),
            brownfox::Rectangle::new(13, -8, 5, 5),
          ],
          "pixelart/maptip/building/top/center.png".to_string(),
          "pixelart/maptip/building/top/left.png".to_string(),
          "pixelart/maptip/building/top/top.png".to_string(),
          "pixelart/maptip/building/top/right.png".to_string(),
          "pixelart/maptip/building/middle/center.png".to_string(),
          "pixelart/maptip/building/top/top-left.png".to_string(),
          "pixelart/maptip/building/top/top-right.png".to_string(),
          "pixelart/maptip/building/middle/left.png".to_string(),
          "pixelart/maptip/building/middle/right.png".to_string(),
          "pixelart/maptip/building/top/top-left.png".to_string(),
          "pixelart/maptip/building/top/top-right.png".to_string(),
          "pixelart/maptip/building/middle/left.png".to_string(),
          "pixelart/maptip/building/middle/right.png".to_string(),
        )),
      ),
      (
        brownfox::Control::Immovable(brownfox::Immovable::new()),
        object::Object::Maptip(object::maptip::new(
          0,
          0,
          0,
          16,
          16,
          vec![
            brownfox::Rectangle::new(2, -4, 5, 10),
            brownfox::Rectangle::new(13, -4, 5, 10),
          ],
          "pixelart/maptip/building/bottom/center.png".to_string(),
          "pixelart/maptip/building/bottom/left.png".to_string(),
          "pixelart/maptip/building/middle/center.png".to_string(),
          "pixelart/maptip/building/bottom/right.png".to_string(),
          "pixelart/maptip/building/bottom/bottom.png".to_string(),
          "pixelart/maptip/building/middle/left.png".to_string(),
          "pixelart/maptip/building/middle/right.png".to_string(),
          "pixelart/maptip/building/bottom/bottom-left.png".to_string(),
          "pixelart/maptip/building/bottom/bottom-right.png".to_string(),
          "pixelart/maptip/building/middle/left.png".to_string(),
          "pixelart/maptip/building/middle/right.png".to_string(),
          "pixelart/maptip/building/bottom/bottom-left.png".to_string(),
          "pixelart/maptip/building/bottom/bottom-right.png".to_string(),
        )),
      ),
      (
        brownfox::Control::Immovable(brownfox::Immovable::new()),
        object::Object::Maptip(object::maptip::new(
          -8,
          0,
          0,
          32,
          32,
          vec![
            brownfox::Rectangle::new(0, 0, 2, 4),
            brownfox::Rectangle::new(0, 2, 5, 2),
            brownfox::Rectangle::new(3, 0, 2, 4),
          ],
          "pixelart/maptip/tree/center.png".to_string(),
          "pixelart/maptip/tree/left.png".to_string(),
          "pixelart/maptip/tree/top.png".to_string(),
          "pixelart/maptip/tree/right.png".to_string(),
          "pixelart/maptip/tree/bottom.png".to_string(),
          "pixelart/maptip/tree/top-left.png".to_string(),
          "pixelart/maptip/tree/top-right.png".to_string(),
          "pixelart/maptip/tree/bottom-left.png".to_string(),
          "pixelart/maptip/tree/bottom-right.png".to_string(),
          "pixelart/maptip/tree/top-left_inv.png".to_string(),
          "pixelart/maptip/tree/top-right_inv.png".to_string(),
          "pixelart/maptip/tree/bottom-left_inv.png".to_string(),
          "pixelart/maptip/tree/bottom-right_inv.png".to_string(),
        )),
      ),
      (
        brownfox::Control::Immovable(brownfox::Immovable::new()),
        object::Object::Maptip(object::maptip::new(
          8,
          0,
          0,
          32,
          32,
          vec![
            brownfox::Rectangle::new(5, 0, 2, 4),
            brownfox::Rectangle::new(5, 2, 5, 2),
            brownfox::Rectangle::new(8, 0, 2, 4),
          ],
          "pixelart/maptip/tree/center.png".to_string(),
          "pixelart/maptip/tree/left.png".to_string(),
          "pixelart/maptip/tree/top.png".to_string(),
          "pixelart/maptip/tree/right.png".to_string(),
          "pixelart/maptip/tree/bottom.png".to_string(),
          "pixelart/maptip/tree/top-left.png".to_string(),
          "pixelart/maptip/tree/top-right.png".to_string(),
          "pixelart/maptip/tree/bottom-left.png".to_string(),
          "pixelart/maptip/tree/bottom-right.png".to_string(),
          "pixelart/maptip/tree/top-left_inv.png".to_string(),
          "pixelart/maptip/tree/top-right_inv.png".to_string(),
          "pixelart/maptip/tree/bottom-left_inv.png".to_string(),
          "pixelart/maptip/tree/bottom-right_inv.png".to_string(),
        )),
      ),
      (
        brownfox::Control::Immovable(brownfox::Immovable::new()),
        object::Object::Maptip(object::maptip::new(
          -16,
          0,
          0,
          32,
          32,
          vec![
            brownfox::Rectangle::new(0, 5, 11, 3),
          ],
          "pixelart/maptip/tree/center.png".to_string(),
          "pixelart/maptip/tree/left.png".to_string(),
          "pixelart/maptip/tree/top.png".to_string(),
          "pixelart/maptip/tree/right.png".to_string(),
          "pixelart/maptip/tree/bottom.png".to_string(),
          "pixelart/maptip/tree/top-left.png".to_string(),
          "pixelart/maptip/tree/top-right.png".to_string(),
          "pixelart/maptip/tree/bottom-left.png".to_string(),
          "pixelart/maptip/tree/bottom-right.png".to_string(),
          "pixelart/maptip/tree/top-left_inv.png".to_string(),
          "pixelart/maptip/tree/top-right_inv.png".to_string(),
          "pixelart/maptip/tree/bottom-left_inv.png".to_string(),
          "pixelart/maptip/tree/bottom-right_inv.png".to_string(),
        )),
      ),
      (
        brownfox::Control::Immovable(brownfox::Immovable::new()),
        object::Object::Maptip(object::maptip::new(
          0,
          -8,
          0,
          32,
          32,
          vec![
            brownfox::Rectangle::new(0, 3, 1, 1),
            brownfox::Rectangle::new(1, 3, 1, 1),
            brownfox::Rectangle::new(2, 3, 1, 1),
            brownfox::Rectangle::new(3, 3, 1, 1),
            brownfox::Rectangle::new(6, 3, 1, 1),
            brownfox::Rectangle::new(7, 3, 1, 1),
            brownfox::Rectangle::new(8, 3, 1, 1),
            brownfox::Rectangle::new(9, 3, 1, 1),
          ],
          "pixelart/maptip/street-light/front.png".to_string(),
          "pixelart/maptip/street-light/front.png".to_string(),
          "pixelart/maptip/street-light/front.png".to_string(),
          "pixelart/maptip/street-light/front.png".to_string(),
          "pixelart/maptip/street-light/front.png".to_string(),
          "pixelart/maptip/street-light/front.png".to_string(),
          "pixelart/maptip/street-light/front.png".to_string(),
          "pixelart/maptip/street-light/front.png".to_string(),
          "pixelart/maptip/street-light/front.png".to_string(),
          "pixelart/maptip/street-light/front.png".to_string(),
          "pixelart/maptip/street-light/front.png".to_string(),
          "pixelart/maptip/street-light/front.png".to_string(),
          "pixelart/maptip/street-light/front.png".to_string(),
        )),
      ),
      (
        brownfox::Control::Immovable(brownfox::Immovable::new()),
        object::Object::Maptip(object::maptip::new(
          0,
          8,
          0,
          32,
          32,
          vec![
            brownfox::Rectangle::new(0, 4, 1, 1),
            brownfox::Rectangle::new(1, 4, 1, 1),
            brownfox::Rectangle::new(2, 4, 1, 1),
            brownfox::Rectangle::new(3, 4, 1, 1),
            brownfox::Rectangle::new(6, 4, 1, 1),
            brownfox::Rectangle::new(7, 4, 1, 1),
            brownfox::Rectangle::new(8, 4, 1, 1),
            brownfox::Rectangle::new(9, 4, 1, 1),
          ],
          "pixelart/maptip/street-light/back.png".to_string(),
          "pixelart/maptip/street-light/back.png".to_string(),
          "pixelart/maptip/street-light/back.png".to_string(),
          "pixelart/maptip/street-light/back.png".to_string(),
          "pixelart/maptip/street-light/back.png".to_string(),
          "pixelart/maptip/street-light/back.png".to_string(),
          "pixelart/maptip/street-light/back.png".to_string(),
          "pixelart/maptip/street-light/back.png".to_string(),
          "pixelart/maptip/street-light/back.png".to_string(),
          "pixelart/maptip/street-light/back.png".to_string(),
          "pixelart/maptip/street-light/back.png".to_string(),
          "pixelart/maptip/street-light/back.png".to_string(),
          "pixelart/maptip/street-light/back.png".to_string(),
        )),
      ),
      (
        brownfox::Control::Immovable(brownfox::Immovable::new()),
        object::Object::Maptip(object::maptip::new(
          -8,
          0,
          0,
          32,
          32,
          vec![
            brownfox::Rectangle::new(4, 0, 1, 1),
            brownfox::Rectangle::new(4, 1, 1, 1),
            brownfox::Rectangle::new(4, 2, 1, 1),
          ],
          "pixelart/maptip/street-light/right.png".to_string(),
          "pixelart/maptip/street-light/right.png".to_string(),
          "pixelart/maptip/street-light/right.png".to_string(),
          "pixelart/maptip/street-light/right.png".to_string(),
          "pixelart/maptip/street-light/right.png".to_string(),
          "pixelart/maptip/street-light/right.png".to_string(),
          "pixelart/maptip/street-light/right.png".to_string(),
          "pixelart/maptip/street-light/right.png".to_string(),
          "pixelart/maptip/street-light/right.png".to_string(),
          "pixelart/maptip/street-light/right.png".to_string(),
          "pixelart/maptip/street-light/right.png".to_string(),
          "pixelart/maptip/street-light/right.png".to_string(),
          "pixelart/maptip/street-light/right.png".to_string(),
        )),
      ),
      (
        brownfox::Control::Immovable(brownfox::Immovable::new()),
        object::Object::Maptip(object::maptip::new(
          8,
          0,
          0,
          32,
          32,
          vec![
            brownfox::Rectangle::new(5, 0, 1, 1),
            brownfox::Rectangle::new(5, 1, 1, 1),
            brownfox::Rectangle::new(5, 2, 1, 1),
          ],
          "pixelart/maptip/street-light/left.png".to_string(),
          "pixelart/maptip/street-light/left.png".to_string(),
          "pixelart/maptip/street-light/left.png".to_string(),
          "pixelart/maptip/street-light/left.png".to_string(),
          "pixelart/maptip/street-light/left.png".to_string(),
          "pixelart/maptip/street-light/left.png".to_string(),
          "pixelart/maptip/street-light/left.png".to_string(),
          "pixelart/maptip/street-light/left.png".to_string(),
          "pixelart/maptip/street-light/left.png".to_string(),
          "pixelart/maptip/street-light/left.png".to_string(),
          "pixelart/maptip/street-light/left.png".to_string(),
          "pixelart/maptip/street-light/left.png".to_string(),
          "pixelart/maptip/street-light/left.png".to_string(),
        )),
      ),
      (
        brownfox::Control::Player(brownfox::Player::new(0)),
        object::Object::Teiri(object::teiri::new(152, 112, 0)),
      ),
      (
        brownfox::Control::Immovable(brownfox::Immovable::new()),
        object::Object::NPC(object::npc::new(144, 96, 0, "pixelart/verity".to_string())),
      ),
      (
        brownfox::Control::Immovable(brownfox::Immovable::new()),
        object::Object::NPC(object::npc::new(175, 96, 0, "pixelart/emily".to_string())),
      ),
      (
        brownfox::Control::Immovable(brownfox::Immovable::new()),
        object::Object::Drone(object::drone::new(192, 112, 0, "pixelart/mathprobe".to_string())),
      ),
      (
        brownfox::Control::Immovable(brownfox::Immovable::new()),
        object::Object::Drone(object::drone::new(192, 128, 0, "pixelart/lonelygem".to_string())),
      ),
      (
        brownfox::Control::Immovable(brownfox::Immovable::new()),
        object::Object::Drone(object::drone::new(176, 128, 0, "pixelart/security-drone".to_string())),
      ),
    ],
    events: vec![],
  }
}
