sentence =
  adverb_phrases clause adverb_phrases PERIOD
| adverb_phrases clause adverb_phrases CC sentence
| adverb_phrases clause adverb_phrases COMMA sentence;

clause =
  noun_phrase VB
| noun_phrase VB noun_phrase
| noun_phrase VB adjective_phrase
| noun_phrase VB noun_phrase noun_phrase
| noun_phrase VB noun_phrase adjective_phrase;

noun_phrase =
  DT adjective_phrases NN (* singular nouns *)
| adjective_phrases NNS   (* plural nouns *)
| adjective_phrases PRP   (* personal pronouns *);

adjective_phrase =
  JJ;

adjective_phrases =
| adjective_phrase adjective_phrases;

adverb_phrase =
  RB;

adverb_phrases =
| adverb_phrase adverb_phrases;
