sentence =
  clause
| clause CC sentence
| clause COMMA sentence
| clause COMMA RB sentence
| clause RB sentence;

clause =
  noun_phrase VB
| noun_phrase VB noun_phrase
| noun_phrase VB adjective_phrase
| noun_phrase VB noun_phrase noun_phrase
| noun_phrase VB noun_phrase adjective_phrase;

noun_phrase =
  DT NN (* singular nouns *)
| NNS   (* plural nouns *)
| PRP   (* personal pronouns *);

adjective_phrase =
  JJ;

(*
adverb_phrase =
  RB;
*)
