sentence =
  clause PERIOD
| clause CC sentence
| clause COMMA sentence
| clause COMMA RB sentence
| clause RB sentence;

clause =
  noun_phrase VB
| noun_phrase VB noun_phrase
| noun_phrase VB adjective_phrase
| noun_phrase VB noun_phrase noun_phrase
| noun_phrase VB noun_phrase adjective_phrase;

noun_phrase =
  DT adjective_phrases NN (* singular nouns *)
| adjective_phrases NNS   (* plural nouns *)
| adjective_phrases PRP   (* personal pronouns *);

adjective_phrase =
  JJ;

adjective_phrases =
| adjective_phrase adjective_phrases;

(*
adverb_phrase =
  RB;
*)
