use super::*;

pub fn new() -> Map {
    Map {
        x: 0,
        y: 0,
        width: 320,
        height: 240,
        objects: vec![
            (
                brownfox::Control::Repeat(brownfox::Repeat::new(
                    16,
                    vec![
                        brownfox::Input::new(
                            1.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            1.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            -1.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            -1.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                    ],
                )),
                object::Object::NPC(object::npc::new(
                    "map/boston/0000-0000/mob-0000".to_string(),
                    40,
                    60,
                    0,
                    "pixelart/mob/0000".to_string(),
                    Some(vec![
                        (
                            "*:びっくり　テーリじゃない".to_string(),
                            "ボストンに　かえってきたの?".to_string(),
                        ),
                        (
                            "テーリ:うん　ひさしぶり！".to_string(),
                            "いろいろ　ひとだんらくしてさ".to_string(),
                        ),
                        (
                            "*:さしずめ　エマにあいさつ".to_string(),
                            "ってとこじゃない?".to_string(),
                        ),
                        (
                            "テーリ:おおあたり!でも".to_string(),
                            "かのじょ　ねぼうしたみたいで".to_string(),
                        ),
                        (
                            "テーリ:じかんつぶしてるとこ".to_string(),
                            "4ねんぶりだしわるくないかな".to_string(),
                        ),
                    ]),
                )),
            ),
            (
                brownfox::Control::Repeat(brownfox::Repeat::new(
                    16,
                    vec![
                        brownfox::Input::new(
                            0.000000,
                            -1.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            1.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            1.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            -1.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                    ],
                )),
                object::Object::NPC(object::npc::new(
                    "map/boston/0000-0000/mob-0001".to_string(),
                    50,
                    70,
                    0,
                    "pixelart/mob/0001".to_string(),
                    None,
                )),
            ),
            (
                brownfox::Control::Repeat(brownfox::Repeat::new(
                    16,
                    vec![
                        brownfox::Input::new(
                            -1.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            -1.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            1.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            1.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                    ],
                )),
                object::Object::NPC(object::npc::new(
                    "map/boston/0000-0000/mob-0002".to_string(),
                    30,
                    80,
                    0,
                    "pixelart/mob/0002".to_string(),
                    None,
                )),
            ),
            (
                brownfox::Control::Repeat(brownfox::Repeat::new(
                    64,
                    vec![
                        brownfox::Input::new(
                            1.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            1.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            -1.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            -1.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                    ],
                )),
                object::Object::Drone(object::drone::new(
                    "map/boston/0000-0000/drone-0000".to_string(),
                    120,
                    90,
                    0,
                    "pixelart/security-drone".to_string(),
                )),
            ),
            (
                brownfox::Control::Repeat(brownfox::Repeat::new(
                    64,
                    vec![
                        brownfox::Input::new(
                            0.000000,
                            1.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            -1.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            -1.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            1.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                    ],
                )),
                object::Object::Drone(object::drone::new(
                    "map/boston/0000-0000/drone-0001".to_string(),
                    200,
                    90,
                    0,
                    "pixelart/security-drone".to_string(),
                )),
            ),
            (
                brownfox::Control::Repeat(brownfox::Repeat::new(
                    64,
                    vec![
                        brownfox::Input::new(
                            -1.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            -1.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            1.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            1.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                    ],
                )),
                object::Object::Drone(object::drone::new(
                    "map/boston/0000-0000/drone-0002".to_string(),
                    120,
                    150,
                    0,
                    "pixelart/security-drone".to_string(),
                )),
            ),
            (
                brownfox::Control::Repeat(brownfox::Repeat::new(
                    64,
                    vec![
                        brownfox::Input::new(
                            0.000000,
                            -1.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            1.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            0.000000,
                            1.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                        brownfox::Input::new(
                            -1.000000,
                            0.000000,
                            &vec![
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false, false, false, false, false,
                                false, false, false, false, false,
                            ],
                        ),
                    ],
                )),
                object::Object::Drone(object::drone::new(
                    "map/boston/0000-0000/drone-0003".to_string(),
                    200,
                    150,
                    0,
                    "pixelart/security-drone".to_string(),
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Transport(object::transport::new(
                    "8c7f0aac97c4aa2f".to_string(),
                    0,
                    -1,
                    320,
                    1,
                    "map/boston/0000-FFFF.json".to_string(),
                    0,
                    224,
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Transport(object::transport::new(
                    "b716a675d821ccc0".to_string(),
                    0,
                    -1,
                    1,
                    240,
                    "map/boston/FFFF-0000.json".to_string(),
                    304,
                    0,
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Transport(object::transport::new(
                    "9a4eb343dba252fb".to_string(),
                    320,
                    0,
                    1,
                    240,
                    "map/boston/0001-0000.json".to_string(),
                    16,
                    0,
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Animated(object::animated::new(
                    "8b7d76c3d8e57d67".to_string(),
                    8,
                    vec![
                        object::Object::Maptip(object::maptip::new(
                            "6c74a4099fa1ded3".to_string(),
                            -16,
                            -16,
                            -1500,
                            16,
                            16,
                            vec![brownfox::Rectangle::new(0, 0, 22, 3)],
                            "pixelart/maptip/water/".to_string(),
                            "/0.png".to_string(),
                        )),
                        object::Object::Maptip(object::maptip::new(
                            "a55951156266d6f2".to_string(),
                            -16,
                            -16,
                            -1500,
                            16,
                            16,
                            vec![brownfox::Rectangle::new(0, 0, 22, 3)],
                            "pixelart/maptip/water/".to_string(),
                            "/1.png".to_string(),
                        )),
                        object::Object::Maptip(object::maptip::new(
                            "7005b7244c2b3a57".to_string(),
                            -16,
                            -16,
                            -1500,
                            16,
                            16,
                            vec![brownfox::Rectangle::new(0, 0, 22, 3)],
                            "pixelart/maptip/water/".to_string(),
                            "/2.png".to_string(),
                        )),
                        object::Object::Maptip(object::maptip::new(
                            "e44b3c460e84bdd8".to_string(),
                            -16,
                            -16,
                            -1500,
                            16,
                            16,
                            vec![brownfox::Rectangle::new(0, 0, 22, 3)],
                            "pixelart/maptip/water/".to_string(),
                            "/3.png".to_string(),
                        )),
                        object::Object::Maptip(object::maptip::new(
                            "f6b29a5845cccd8c".to_string(),
                            -16,
                            -16,
                            -1500,
                            16,
                            16,
                            vec![brownfox::Rectangle::new(0, 0, 22, 3)],
                            "pixelart/maptip/water/".to_string(),
                            "/4.png".to_string(),
                        )),
                        object::Object::Maptip(object::maptip::new(
                            "6229393a7a4842c1".to_string(),
                            -16,
                            -16,
                            -1500,
                            16,
                            16,
                            vec![brownfox::Rectangle::new(0, 0, 22, 3)],
                            "pixelart/maptip/water/".to_string(),
                            "/5.png".to_string(),
                        )),
                        object::Object::Maptip(object::maptip::new(
                            "caae7de6cfea4a27".to_string(),
                            -16,
                            -16,
                            -1500,
                            16,
                            16,
                            vec![brownfox::Rectangle::new(0, 0, 22, 3)],
                            "pixelart/maptip/water/".to_string(),
                            "/6.png".to_string(),
                        )),
                        object::Object::Maptip(object::maptip::new(
                            "8765a8577adfc8ae".to_string(),
                            -16,
                            -16,
                            -1500,
                            16,
                            16,
                            vec![brownfox::Rectangle::new(0, 0, 22, 3)],
                            "pixelart/maptip/water/".to_string(),
                            "/7.png".to_string(),
                        )),
                    ],
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Maptip(object::maptip::new(
                    "916b5e58648d8b51".to_string(),
                    0,
                    0,
                    -1000,
                    16,
                    16,
                    vec![brownfox::Rectangle::new(-1, 1, 22, 4)],
                    "pixelart/maptip/ground/".to_string(),
                    ".png".to_string(),
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Maptip(object::maptip::new(
                    "ecf3e6a5d6094219".to_string(),
                    0,
                    0,
                    -1000,
                    16,
                    16,
                    vec![
                        brownfox::Rectangle::new(6, -1, 8, 17),
                        brownfox::Rectangle::new(-1, 6, 22, 8),
                    ],
                    "pixelart/maptip/asphalt/".to_string(),
                    ".png".to_string(),
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Maptip(object::maptip::new(
                    "122f6b4d565f9848".to_string(),
                    0,
                    0,
                    -1000,
                    16,
                    16,
                    vec![
                        brownfox::Rectangle::new(3, -1, 4, 8),
                        brownfox::Rectangle::new(-1, 3, 4, 4),
                        brownfox::Rectangle::new(13, -1, 4, 8),
                        brownfox::Rectangle::new(17, 3, 4, 4),
                        brownfox::Rectangle::new(-1, 13, 8, 4),
                        brownfox::Rectangle::new(13, 13, 8, 4),
                    ],
                    "pixelart/maptip/mortar/".to_string(),
                    ".png".to_string(),
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Maptip(object::maptip::new(
                    "164e1b09a5ee9794".to_string(),
                    92,
                    0,
                    -1000,
                    32,
                    32,
                    vec![
                        brownfox::Rectangle::new(0, 0, 1, 3),
                        brownfox::Rectangle::new(0, 6, 1, 2),
                    ],
                    "pixelart/maptip/street-light/right/".to_string(),
                    ".png".to_string(),
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Maptip(object::maptip::new(
                    "52d08735e4513d0".to_string(),
                    196,
                    0,
                    -1000,
                    32,
                    32,
                    vec![
                        brownfox::Rectangle::new(0, 0, 1, 3),
                        brownfox::Rectangle::new(0, 6, 1, 2),
                    ],
                    "pixelart/maptip/street-light/left/".to_string(),
                    ".png".to_string(),
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Maptip(object::maptip::new(
                    "d52692f3f5081ec5".to_string(),
                    0,
                    80,
                    -1000,
                    32,
                    32,
                    vec![
                        brownfox::Rectangle::new(0, 0, 3, 1),
                        brownfox::Rectangle::new(7, 0, 3, 1),
                    ],
                    "pixelart/maptip/street-light/front/".to_string(),
                    ".png".to_string(),
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Maptip(object::maptip::new(
                    "c73547fe23ee074f".to_string(),
                    0,
                    180,
                    -1000,
                    32,
                    32,
                    vec![
                        brownfox::Rectangle::new(0, 0, 3, 1),
                        brownfox::Rectangle::new(7, 0, 3, 1),
                    ],
                    "pixelart/maptip/street-light/back/".to_string(),
                    ".png".to_string(),
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Maptip(object::maptip::new(
                    "deb91dafdebe09c0".to_string(),
                    -16,
                    0,
                    -1000,
                    32,
                    32,
                    vec![
                        brownfox::Rectangle::new(-1, 0, 4, 2),
                        brownfox::Rectangle::new(8, 0, 4, 2),
                        brownfox::Rectangle::new(-1, 6, 4, 2),
                        brownfox::Rectangle::new(7, 6, 2, 2),
                    ],
                    "pixelart/maptip/tree/".to_string(),
                    ".png".to_string(),
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Maptip(object::maptip::new(
                    "fa86bb52793e6063".to_string(),
                    256,
                    64,
                    1000,
                    16,
                    16,
                    vec![brownfox::Rectangle::new(0, 0, 8, 6)],
                    "pixelart/maptip/building/top/".to_string(),
                    ".png".to_string(),
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Maptip(object::maptip::new(
                    "cc95a7d8cd087cb1".to_string(),
                    256,
                    64,
                    1000,
                    16,
                    16,
                    vec![brownfox::Rectangle::new(0, 5, 8, 20)],
                    "pixelart/maptip/building/bottom/".to_string(),
                    ".png".to_string(),
                )),
            ),
        ],
    }
}
