use super::*;

pub fn new() -> Map {
    Map {
        x: 0,
        y: 0,
        width: 320,
        height: 240,
        objects: vec![
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Transport(object::transport::new(
                    "8c7f0aac97c4aa2f".to_string(),
                    320,
                    0,
                    1,
                    240,
                    "map/boston/0000-0000.json".to_string(),
                    16,
                    0,
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Animated(object::animated::new(
                    "b716a675d821ccc0".to_string(),
                    8,
                    vec![
                        object::Object::Maptip(object::maptip::new(
                            "9a4eb343dba252fb".to_string(),
                            -16,
                            -16,
                            -1500,
                            16,
                            16,
                            vec![brownfox::Rectangle::new(0, 0, 22, 3)],
                            "pixelart/maptip/water/".to_string(),
                            "/0.png".to_string(),
                        )),
                        object::Object::Maptip(object::maptip::new(
                            "8b7d76c3d8e57d67".to_string(),
                            -16,
                            -16,
                            -1500,
                            16,
                            16,
                            vec![brownfox::Rectangle::new(0, 0, 22, 3)],
                            "pixelart/maptip/water/".to_string(),
                            "/1.png".to_string(),
                        )),
                        object::Object::Maptip(object::maptip::new(
                            "6c74a4099fa1ded3".to_string(),
                            -16,
                            -16,
                            -1500,
                            16,
                            16,
                            vec![brownfox::Rectangle::new(0, 0, 22, 3)],
                            "pixelart/maptip/water/".to_string(),
                            "/2.png".to_string(),
                        )),
                        object::Object::Maptip(object::maptip::new(
                            "a55951156266d6f2".to_string(),
                            -16,
                            -16,
                            -1500,
                            16,
                            16,
                            vec![brownfox::Rectangle::new(0, 0, 22, 3)],
                            "pixelart/maptip/water/".to_string(),
                            "/3.png".to_string(),
                        )),
                        object::Object::Maptip(object::maptip::new(
                            "7005b7244c2b3a57".to_string(),
                            -16,
                            -16,
                            -1500,
                            16,
                            16,
                            vec![brownfox::Rectangle::new(0, 0, 22, 3)],
                            "pixelart/maptip/water/".to_string(),
                            "/4.png".to_string(),
                        )),
                        object::Object::Maptip(object::maptip::new(
                            "e44b3c460e84bdd8".to_string(),
                            -16,
                            -16,
                            -1500,
                            16,
                            16,
                            vec![brownfox::Rectangle::new(0, 0, 22, 3)],
                            "pixelart/maptip/water/".to_string(),
                            "/5.png".to_string(),
                        )),
                        object::Object::Maptip(object::maptip::new(
                            "f6b29a5845cccd8c".to_string(),
                            -16,
                            -16,
                            -1500,
                            16,
                            16,
                            vec![brownfox::Rectangle::new(0, 0, 22, 3)],
                            "pixelart/maptip/water/".to_string(),
                            "/6.png".to_string(),
                        )),
                        object::Object::Maptip(object::maptip::new(
                            "6229393a7a4842c1".to_string(),
                            -16,
                            -16,
                            -1500,
                            16,
                            16,
                            vec![brownfox::Rectangle::new(0, 0, 22, 3)],
                            "pixelart/maptip/water/".to_string(),
                            "/7.png".to_string(),
                        )),
                    ],
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Maptip(object::maptip::new(
                    "caae7de6cfea4a27".to_string(),
                    0,
                    0,
                    -1000,
                    16,
                    16,
                    vec![brownfox::Rectangle::new(-1, 1, 22, 4)],
                    "pixelart/maptip/ground/".to_string(),
                    ".png".to_string(),
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Maptip(object::maptip::new(
                    "8765a8577adfc8ae".to_string(),
                    0,
                    0,
                    -999,
                    16,
                    16,
                    vec![brownfox::Rectangle::new(-1, 6, 22, 8)],
                    "pixelart/maptip/asphalt/".to_string(),
                    ".png".to_string(),
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Maptip(object::maptip::new(
                    "916b5e58648d8b51".to_string(),
                    0,
                    0,
                    -998,
                    16,
                    16,
                    vec![
                        brownfox::Rectangle::new(-1, 3, 22, 4),
                        brownfox::Rectangle::new(-1, 13, 22, 4),
                    ],
                    "pixelart/maptip/mortar/".to_string(),
                    ".png".to_string(),
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Maptip(object::maptip::new(
                    "ecf3e6a5d6094219".to_string(),
                    0,
                    80,
                    -997,
                    32,
                    32,
                    vec![brownfox::Rectangle::new(0, 0, 10, 1)],
                    "pixelart/maptip/street-light/front/".to_string(),
                    ".png".to_string(),
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Maptip(object::maptip::new(
                    "122f6b4d565f9848".to_string(),
                    0,
                    180,
                    -996,
                    32,
                    32,
                    vec![brownfox::Rectangle::new(0, 0, 10, 1)],
                    "pixelart/maptip/street-light/back/".to_string(),
                    ".png".to_string(),
                )),
            ),
            (
                brownfox::Control::Immovable(brownfox::Immovable::new()),
                object::Object::Maptip(object::maptip::new(
                    "164e1b09a5ee9794".to_string(),
                    -16,
                    0,
                    -995,
                    32,
                    32,
                    vec![brownfox::Rectangle::new(-1, 0, 13, 2)],
                    "pixelart/maptip/tree/".to_string(),
                    ".png".to_string(),
                )),
            ),
        ],
    }
}
