#!/usr/bin/ruby

require "json"

episode = JSON.parse ARGF.read

printf "use super::*;\n"
printf "\n"
printf "pub fn new() -> Hijack {\n"
printf "  Hijack {\n"
printf "    x: %d,\n", episode["x"]
printf "    y: %d,\n", episode["y"]
printf "    width: %d,\n", episode["width"]
printf "    height: %d,\n", episode["height"]
printf "    objects: vec![\n"

def generate_object object
  case object["type"]
  when "maptip"
    printf "        object::Object::Maptip(object::maptip::new(\n"
    printf "          %d,\n", object["x"]
    printf "          %d,\n", object["y"]
    printf "          %d,\n", object["z"]
    printf "          %d,\n", object["width"]
    printf "          %d,\n", object["height"]
    printf "          vec![\n"
    object["rectangles"].each do |rectangle|
      printf "            brownfox::Rectangle::new(%d, %d, %d, %d),\n", rectangle["x"], rectangle["y"], rectangle["width"], rectangle["height"]
    end
    printf "          ],\n"
    printf "          \"%s\".to_string(),\n", object["prefix"]
    printf "          \"%s\".to_string(),\n", object["suffix"]
    printf "        ))\n"
  when "teiri"
    printf "        object::Object::Teiri(object::teiri::new(%d, %d, %d))\n", object["x"], object["y"], object["z"]
  when "npc"
    printf "        object::Object::NPC(object::npc::new(%d, %d, %d, \"%s\".to_string()))\n", object["x"], object["y"], object["z"], object["name"]
  when "drone"
    printf "        object::Object::Drone(object::drone::new(%d, %d, %d, \"%s\".to_string()))\n", object["x"], object["y"], object["z"], object["name"]
  when "animated"
    printf "        object::Object::Animated(object::animated::new(\n"
    printf "          %d,\n", object["i"]
    printf "          vec![\n", object["i"]
    object["objects"].each do |obj|
      generate_object obj
      printf "        ,\n"
    end
    printf "        ])),\n"
  end
end

episode["objects"].each do |object|
  printf "      (\n"

  case object["control"]["type"]
  when "player"
    printf "        brownfox::Control::Player(brownfox::Player::new(%d)),\n", object["control"]["i"]
  when "immovable"
    printf "        brownfox::Control::Immovable(brownfox::Immovable::new()),\n"
  end

  generate_object object["object"]

  printf "      ),\n"
end

printf "    ],\n"
printf "    events: vec![],\n"
printf "  }\n"
printf "}\n"
