[package]
name = "hijack"
version = "0.1.0"
authors = ["bydriv <bydriv@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
brownfox = {path = "brownfox"}

[workspace]
members = ["brownfox"]
