#!/bin/sh

TITLE="$1"
HD="$2"
shift 2

for tab in "$@"; do
    test ! -f "$tab" && printf "%s: %s: No such file or directory\n" "$0" "$tab"
done

for tab in "$@"; do
    test ! -f "$tab" && exit 1
done

printf "<!DOCTYPE html>\n"
printf "\n"
printf "<meta charset=\"utf-8\">\n"
printf "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
printf "<title>%s</title>\n" "$TITLE"
printf "\n"

printf "<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/prelude.css\">\n"
printf "<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/github-markdown.css\">\n"
printf "<style>\n"
printf "  div#hd {\n"
printf "    height: 160px;\n"
printf "    margin: 0;\n"
printf "    padding: 0;\n"
printf "\n"
printf "    background-image: url(\"$HD\");\n"
printf "    background-position: center;\n"
printf "  }\n"

for tab in "$@"; do
    TAB="$(basename "$tab" .md)"

    if test "$TAB" != "default"
    then
        printf "  div#%s:target ~ div#index > div#default-index-group > div#%s-index {\n" "$TAB" "$TAB"
        printf "    color: #000000;\n"
        printf "    background-color: #00FFFF;\n"
        printf "  }\n"
        printf "\n"
        printf "  div#%s:target ~ div#contents > div#%s-contents {\n" "$TAB" "$TAB"
        printf "    max-height: none;\n"
        printf "\n"
        printf "    top: 0;\n"
        printf "    z-index: -1000;\n"
        printf "    opacity: 1;\n"
        printf "  }\n"
    fi
done

printf "</style>\n"

printf "<div id=\"container\">\n"
printf "  <div id=\"home\" class=\"default anchor\"></div>\n"

for tab in "$@"; do
    TAB="$(basename "$tab" .md)"

    if test "$TAB" != "default"
    then
        printf "  <div id=\"%s\" class=\"anchor\"></div>\n" "$TAB"
    fi
done

printf "  <div id=\"hd\"></div>\n"
printf "  <h1>%s</h1>\n" "$TITLE"
printf "  <div id=\"index\">\n"
printf "    <div id=\"default-index-group\" class=\"default level-0 index-group\">\n"

for tab in "$@"; do
    TAB="$(basename "$tab" .md)"

    if test "$TAB" = "default"
    then
        printf "      <div id=\"default-index\" class=\"default index\">"
        printf "<a href=\"#home\">HOME</a>"
        printf "</div>\n"
    else
        printf "      <div id=\"%s-index\" class=\"index\">" "$TAB"
        printf "<a href=\"#%s\">$(echo "$TAB" | tr a-z A-Z)</a>" "$TAB"
        printf "</div>\n"
    fi
done

printf "    </div>\n"
printf "  </div>\n"
printf "  <div id=\"contents\">\n"

for tab in "$@"; do
    TAB="$(basename "$tab" .md)"

    if test "$TAB" = "default"
    then
        printf "    <div id=\"default-contents\" class=\"default contents\">\n"
        printf "      <div class=\"markdown-body\">\n"
        pandoc "$tab"
        printf "      </div>\n"
        printf "    </div>\n"
    else
        printf "    <div id=\"%s-contents\" class=\"contents\">\n" "$TAB"
        printf "      <div class=\"markdown-body\">\n"
        pandoc "$tab"
        printf "      </div>\n"
        printf "    </div>\n"
    fi
done

printf "  </div>\n"
printf "</div>\n"
